### ISSUE TITLE
Criar personas

### ISSUE THREAD

**Issue by NicolasCBV** [ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus#30]
Criar no mínimo 6 personas para preencher a seção 4.1.
Gerador de personas a ser usado como base: [https://www.geradordepersonas.com.br/](https://www.geradordepersonas.com.br/)

Responsáveis: @juliamascari e @HgBertani  
Revisores: @Vinicius-O-Neves e @NicolasCBV 
Entrega: terça-feira - 15/10

**Comment by juliamascari** [comment]
Três personas (profissionais da saúde) criados em: [Link](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/blob/personas/docs/design.md) 

Branch "personas"
